### ISSUE TITLE
Build failure due to missing TASK_SHEAR_BEVAMETERAction.h file

### ISSUE THREAD

**Issue by oceank** [nasa/ow_autonomy#79]
Description: when building ow_plexil for the new version of OWLAT using the build option, -DOWLAT=on, we observed the following build error.

> Errors     << ow_plexil:make /home/sonam/oceanwaters_ws/logs/ow_plexil/build.make.001.log        
> In file included from /home/sonam/oceanwaters_ws/src/ow_autonomy/ow_plexil/src/plexil-adapter/OwlatAdapter.cpp:9:
> /home/sonam/oceanwaters_ws/src/ow_autonomy/ow_plexil/src/plexil-adapter/OwlatInterface.h:33:10: fatal error: **owlat_sim_msgs/TASK_SHEAR_BEVAMETERAction.h**: No such file or directory
>    33 | #include <owlat_sim_msgs/TASK_SHEAR_BEVAMETERAction.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.

Reproduce Steps:

1. install the new version (or version 2) of OWLAT
2. follow setup and build steps in ow_simulator repo (use the master branch of release 9 for all four repos)
3. rebuild ow_plexil with the build option, -DOWLAT=ON

Cause Discovery:
According to the user guide of the new version of OWLAT, OWLAT does not support shear bevameter. So, the previous header file is removed.

Posible Workaround:
Comment out/remove any pieces of code related to shear bevameter in ow_autonomy repo, and then rebuild.

**Comment by kmdalal** [comment]
Thanks for the report @oceank .  I'll admit you're a step ahead of us.  We have not yet gotten OWLAT on our systems due to a problem associated with the default Python version being 2 on our systems.  I hope to have this problem resolved as early as tomorrow, and can than reproduce and fix your problem.   Please use the workaround you've found in the meantime - it is sound.

**Comment by kmdalal** [comment]
Problem fixed, as suggested, on noetic-devel branch.
